import Foundation

// iOS 26+ FoundationModels are not yet fully available on Xcode 16 for simulation.
// To bypass compiler issues during the transition, we define these macros for backwards compatibility.

#if !canImport(FoundationModels)

public enum FoundationModelsError: Error {
    case unavailable
    case generationFailed
}

/// A macro marker indicating a type can be generated by a Foundation Model
@attached(extension, conformances: GenerableProtocol)
public macro Generable() = #externalMacro(module: "FoundationModelsMacros", type: "GenerableMacro")

public protocol GenerableProtocol {}

/// A macro marker providing instructions for the Foundation Model
@attached(peer)
public macro Guide(description: String) = #externalMacro(module: "FoundationModelsMacros", type: "GuideMacro")

#endif

